[program:apphub]
command=uvicorn src.main:app --host 0.0.0.0 --port 8080
autostart=true
autorestart=true
user=root
directory=/websoft9/apphub
priority=40
stdout_logfile=/var/log/supervisor/apphub.log
stderr_logfile=/var/log/supervisor/apphub-error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB

[program:apphub-media]
command=uvicorn src.media:app --host 0.0.0.0 --port 8081
autostart=true
autorestart=true
user=root
directory=/websoft9/apphub
priority=41
stdout_logfile=/var/log/supervisor/apphub-media.log
stderr_logfile=/var/log/supervisor/apphub-media-error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB

[program:apphub-cron]
command=cron -f
autostart=true
autorestart=true
user=root
priority=42
stdout_logfile=/var/log/supervisor/apphub-cron.log
stderr_logfile=/var/log/supervisor/apphub-cron-error.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
