[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=10MB
logfile_backups=3
loglevel=info
user=root

[program:dbus]
command=/usr/bin/dbus-daemon --system --nofork --nopidfile
priority=10
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/dbus.log
stderr_logfile=/var/log/supervisor/dbus-error.log

[program:sshd]
command=/usr/sbin/sshd -D -e
priority=15
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/sshd.log
stderr_logfile=/var/log/supervisor/sshd-error.log

[program:cockpit-ws]
command=/usr/lib/cockpit/cockpit-ws --no-tls --port 9090 --local-ssh
priority=20
autostart=true
autorestart=true
user=root
stdout_logfile=/var/log/supervisor/cockpit-ws.log
stderr_logfile=/var/log/supervisor/cockpit-ws-error.log

[program:portainer]
command=/portainer --data /portainer_data --bind :9000 --hide-label owner=websoft9
priority=25
autostart=true
autorestart=true
user=root
stdout_logfile=/var/log/supervisor/portainer.log
stderr_logfile=/var/log/supervisor/portainer-error.log

[program:gitea]
command=/usr/local/bin/gitea web --config /etc/gitea/app.ini
directory=/var/lib/gitea
environment=HOME="/var/lib/gitea",USER="git",GITEA_WORK_DIR="/var/lib/gitea"
priority=26
autostart=true
autorestart=true
user=git
stdout_logfile=/var/log/supervisor/gitea.log
stderr_logfile=/var/log/supervisor/gitea-error.log

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
priority=30
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx-error.log
