# Edit Module - Module Editor Configuration
name: "edit-module"
description: "Edit existing BMAD modules (structure, agents, workflows, documentation) while following all best practices"
author: "BMad"

# Critical variables load from config_source
config_source: "{project-root}/_bmad/bmb/config.yaml"
communication_language: "{config_source}:communication_language"
user_name: "{config_source}:user_name"

# Required Data Files - Critical for understanding module conventions
module_structure_guide: "{project-root}/_bmad/bmb/workflows/create-module/module-structure.md"

# Related workflow editors
agent_editor: "{project-root}/_bmad/bmb/workflows/edit-agent/workflow.yaml"
workflow_editor: "{project-root}/_bmad/bmb/workflows/edit-workflow/workflow.yaml"

# Reference examples - for learning patterns
bmm_module_dir: "{project-root}/_bmad/bmm/"
bmb_module_dir: "{project-root}/_bmad/bmb/"
cis_module_dir: "{project-root}/_bmad/cis/"
existing_agents_dir: "{project-root}/_bmad/*/agents/"
existing_workflows_dir: "{project-root}/_bmad/*/workflows/"

# Module path and component files
installed_path: "{project-root}/_bmad/bmb/workflows/edit-module"
template: false # This is an action workflow - no template needed
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

standalone: true

# Web bundle configuration