# Workflow Init - Initial Game Project Setup
name: workflow-init
description: "Initialize a new BMGD game project by determining level, type, and creating workflow path"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmgd/config.yaml"
output_folder: "{config_source}:output_folder"
implementation_artifacts: "{config_source}:implementation_artifacts"
user_name: "{config_source}:user_name"
project_name: "{config_source}:project_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:game_dev_experience"
date: system-generated

# Workflow components
installed_path: "{project-root}/_bmad/bmgd/workflows/workflow-status/init"
instructions: "{installed_path}/instructions.md"
template: "{project-root}/_bmad/bmgd/workflows/workflow-status/workflow-status-template.yaml"

# Path data files
path_files: "{project-root}/_bmad/bmgd/workflows/workflow-status/paths/"

# Output configuration
default_output_file: "{output_folder}/bmgd-workflow-status.yaml"

standalone: true