server {
  listen 8889 default_server;
  listen [::]:8889 default_server;

  listen 8890 ssl default_server;
  listen [::]:8890 ssl default_server;

  server_name _;

  include /etc/custom/custom_ssl.conf;
  include /etc/websoft9/platform-gateway/platform-gateway-boundary.conf;
  include /etc/websoft9/platform-gateway/platform-gateway-routes.conf;
}