server {
  listen 8889 default_server;
  listen [::]:8889 default_server;

  listen 8890 ssl default_server;
  listen [::]:8890 ssl default_server;

  server_name  _;

  include /etc/custom/custom_ssl.conf;
  include /etc/websoft9/platform-gateway-boundary.conf;

  access_log /data/logs/proxy-host-1_access.log proxy;
  error_log /data/logs/proxy-host-1_error.log warn;

  include /etc/websoft9/platform-gateway-routes.conf;

  # Custom
  include /data/nginx/custom/server_proxy[.]conf;
}
