[unix_http_server]
file=/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=false
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
pidfile=/run/supervisord.pid
user=root

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///run/supervisor.sock

[program:platform-gateway]
command=/websoft9/script/platform-start-gateway.sh
autostart=true
autorestart=true
user=root
stdout_logfile=/var/log/supervisord.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/supervisord.log
stderr_logfile_maxbytes=0

[program:apphub-api]
command=python3 -m uvicorn src.main:app --host 0.0.0.0 --port 8080 --log-config /etc/supervisor/conf.d/logging_config.yaml
directory=/websoft9/apphub
autostart=true
autorestart=true
user=root
stdout_logfile=/var/log/supervisord.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/supervisord.log
stderr_logfile_maxbytes=0

[program:apphub-media]
command=python3 -m uvicorn src.media:app --host 0.0.0.0 --port 8081
directory=/websoft9/apphub
autostart=true
autorestart=true
user=root
stdout_logfile=/var/log/supervisord.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/supervisord.log
stderr_logfile_maxbytes=0

[program:files-agent]
command=python3 -m uvicorn src.files_agent:app --host 127.0.0.1 --port 8091
directory=/websoft9/apphub
autostart=true
autorestart=true
user=root
stdout_logfile=/var/log/supervisord.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/supervisord.log
stderr_logfile_maxbytes=0

[program:gitea]
command=/websoft9/script/platform-start-gitea.sh
autostart=true
autorestart=true
user=root
stdout_logfile=/var/log/websoft9/gitea/service.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/websoft9/gitea/service.log
stderr_logfile_maxbytes=0

[program:portainer]
command=/websoft9/script/platform-start-portainer.sh --data /data/portainer
autostart=true
autorestart=true
user=root
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/websoft9/portainer/service.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/websoft9/portainer/service.log
stderr_logfile_maxbytes=0

[program:npm-backend]
command=/websoft9/script/platform-start-npm-backend.sh
autostart=true
autorestart=true
user=root
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/websoft9/nginx-proxy-manager/backend.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/websoft9/nginx-proxy-manager/backend.log
stderr_logfile_maxbytes=0

[program:npm-nginx]
command=/websoft9/script/platform-start-npm-nginx.sh
autostart=true
autorestart=true
user=root
stdout_logfile=/var/log/websoft9/nginx-proxy-manager/nginx.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/websoft9/nginx-proxy-manager/nginx.log
stderr_logfile_maxbytes=0

[program:cron]
command=cron -f
autostart=true
autorestart=true
user=root
stdout_logfile=/var/log/supervisord.log
stdout_logfile_maxbytes=0
stderr_logfile=/var/log/supervisord.log
stderr_logfile_maxbytes=0