# This is Cloud-Installer template of Websoft9
# Task priority: pre_tasks > role > tasks > post_task
# Variable priority: vars_files > vars

- name: RabbitMQ
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml
  
  vars_prompt:
    - name: 'rabbitmq_selection'
      prompt: "Choose the RabbitMQ distribution \n
      1: RabbitMQ 5 Classic\n
      2: RabbitMQ Artemis\n"
      private: no
      default: 1

  vars:
    rabbitmq_select:
      '1': "classic"
      '2': "artemis"

    rabbitmq_distribution: "{{rabbitmq_select[rabbitmq_selection]}}"
  
  pre_tasks:
    - debug:
        msg: Will install {{rabbitmq_distribution}}

  roles:
    - {role: role_common, tags: "role_common"}  
    - {role: role_cloud, tags: "role_cloud"}  
    - {role: role_jdk, tags: "role_jdk"}  
    - {role: rabbitmq, tags: "rabbitmq"}
    - {role: role_preend, tags: "preend"}
    - {role: role_end, tags: "role_end"}
