user root;
worker_processes auto;
pid /run/websoft9/platform-gateway.pid;

events {
  worker_connections 1024;
}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  sendfile on;
  tcp_nopush on;
  tcp_nodelay on;
  keepalive_timeout 65;
  types_hash_max_size 4096;
  server_tokens off;

  access_log /data/logs/platform-gateway-access.log;
  error_log /data/logs/platform-gateway-error.log warn;

  include /etc/websoft9/platform-gateway/default.conf;
}