#!/bin/bash
# build-bundle.sh - release bundler
# Inline lib/*.sh into the entry scripts and emit self-contained distributable scripts.
# 
# Input: install/install.sh, install/uninstall.sh (with WEBSOFT9_LIB_SOURCING marker block)
# Output: install/dist/install.sh, install/dist/uninstall.sh (self-contained)
# 
# Usage:
#   bash install/build-bundle.sh [--channel <release|rc|dev>] [output directory]
#   Default channel: release  Default output directory: install/dist

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
LIB_DIR="${HERE}/lib"

# Parse options.
OPT_CHANNEL="release"
OUT_DIR=""

while [ $# -gt 0 ]; do
  case "$1" in
    --channel) OPT_CHANNEL="$2"; shift 2 ;;
    --channel=*) OPT_CHANNEL="${1#*=}"; shift ;;
    -*) log "Error: unknown option $1"; exit 2 ;;
    *) OUT_DIR="$1"; shift ;;
  esac
done

[ -z "$OUT_DIR" ] && OUT_DIR="${HERE}/dist"
[ -z "$OPT_CHANNEL" ] && OPT_CHANNEL="release"

case "$OPT_CHANNEL" in
  release|rc|dev) ;;
  *) log "Error: unsupported channel ${OPT_CHANNEL} (expected release, rc, or dev)"; exit 2 ;;
esac

BEGIN_MARK="# >>> WEBSOFT9_LIB_SOURCING >>>"
END_MARK="# <<< WEBSOFT9_LIB_SOURCING <<<"

# Library inline order. Dependencies require common.sh first.
LIB_ORDER=(
  common.sh
  detect.sh
  legacy-discovery.sh
  backup.sh
  validate.sh
  install-fresh.sh
  upgrade-modern.sh
  upgrade-legacy.sh
  uninstall.sh
)

log() { echo "[build-bundle] $*"; }

# Emit one library file without its shebang.
emit_lib() {
  local f="$1"
  echo "# ----- inlined: lib/${f} -----"
  # Drop the first shebang line when present.
  sed '1{/^#!/d;}' "${LIB_DIR}/${f}"
  echo ""
}

# Build one bundled entrypoint by replacing the marker block with inlined libs.
build_one() {
  local entry="$1" out="$2"
  local in_block=0 inlined=0

  : >"$out"
  while IFS= read -r line || [ -n "$line" ]; do
    if [ "$line" = "$BEGIN_MARK" ]; then
      in_block=1
      {
        echo "# ===== Websoft9 self-contained bundle (auto-generated by build-bundle.sh) ====="
        echo "# Do not edit this file by hand. Edit install/install.sh and install/lib/*.sh instead."
        local lf
        for lf in "${LIB_ORDER[@]}"; do
          emit_lib "$lf"
        done
        echo "# ===== end inlined libs ====="
      } >>"$out"
      inlined=1
      continue
    fi
    if [ "$line" = "$END_MARK" ]; then
      in_block=0
      continue
    fi
    [ "$in_block" -eq 1 ] && continue
    printf '%s\n' "$line" >>"$out"
  done <"$entry"

  if [ "$inlined" -ne 1 ]; then
    log "Error: marker block ${BEGIN_MARK} not found in ${entry}"
    return 1
  fi
  chmod +x "$out"
  log "Generated self-contained bundle: $out"
}

main() {
  mkdir -p "$OUT_DIR"
  build_one "${HERE}/install.sh"   "${OUT_DIR}/install.sh"
  build_one "${HERE}/uninstall.sh" "${OUT_DIR}/uninstall.sh"

  # Bake the default channel into the output scripts when needed.
  if [ "$OPT_CHANNEL" != "release" ]; then
    local f
    for f in install.sh uninstall.sh; do
      sed -i "s/^OPT_CHANNEL=\"release\"$/OPT_CHANNEL=\"${OPT_CHANNEL}\"/" "${OUT_DIR}/${f}"
    done
    log "Baked default channel into output: ${OPT_CHANNEL}"
  fi

  # Self-check: syntax plus no leftover source directives.
  local f
  for f in install.sh uninstall.sh; do
    if ! bash -n "${OUT_DIR}/${f}"; then
      log "Error: ${f} failed syntax validation"
      exit 1
    fi
    if grep -Eq '^\s*\.\s+"\$\{W9_LIB_DIR\}' "${OUT_DIR}/${f}"; then
      log "Error: ${f} still contains non-inlined source directives"
      exit 1
    fi
  done
  log "Bundle build completed and self-check passed: ${OUT_DIR}/install.sh, ${OUT_DIR}/uninstall.sh (channel: ${OPT_CHANNEL})"
}

main "$@"
