#!/bin/bash
# build-bundle.sh — 发布构建器（B 方案）
# 将拆分的 lib/*.sh 内联到入口脚本，生成自包含单文件，供制品分发（一次下载即可运行）。
#
# 输入：install/install.sh、install/uninstall.sh（含 WEBSOFT9_LIB_SOURCING 标记块）
# 输出：install/dist/install.sh、install/dist/uninstall.sh（自包含）
#
# 用法：bash install/build-bundle.sh [输出目录]
#   默认输出目录：install/dist

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
LIB_DIR="${HERE}/lib"
OUT_DIR="${1:-${HERE}/dist}"

BEGIN_MARK="# >>> WEBSOFT9_LIB_SOURCING >>>"
END_MARK="# <<< WEBSOFT9_LIB_SOURCING <<<"

# lib 内联顺序（必须满足依赖：common 在最前，路径实现在其后）
LIB_ORDER=(
  common.sh
  detect.sh
  backup.sh
  validate.sh
  install-fresh.sh
  upgrade-modern.sh
  upgrade-legacy.sh
  uninstall.sh
)

log() { echo "[build-bundle] $*"; }

# 去除单个 lib 文件的 shebang 行后输出
emit_lib() {
  local f="$1"
  echo "# ----- inlined: lib/${f} -----"
  # 删除首行 shebang（仅当其为 #! 开头）
  sed '1{/^#!/d;}' "${LIB_DIR}/${f}"
  echo ""
}

# 构建单个入口：把标记块替换为内联 lib，其余原样保留
build_one() {
  local entry="$1" out="$2"
  local in_block=0 inlined=0

  : >"$out"
  while IFS= read -r line || [ -n "$line" ]; do
    if [ "$line" = "$BEGIN_MARK" ]; then
      in_block=1
      {
        echo "# ===== Websoft9 self-contained bundle (auto-generated by build-bundle.sh) ====="
        echo "# 请勿手工编辑此文件；修改源在 install/install.sh 与 install/lib/*.sh"
        local lf
        for lf in "${LIB_ORDER[@]}"; do
          emit_lib "$lf"
        done
        echo "# ===== end inlined libs ====="
      } >>"$out"
      inlined=1
      continue
    fi
    if [ "$line" = "$END_MARK" ]; then
      in_block=0
      continue
    fi
    [ "$in_block" -eq 1 ] && continue
    printf '%s\n' "$line" >>"$out"
  done <"$entry"

  if [ "$inlined" -ne 1 ]; then
    log "错误：未在 ${entry} 找到 ${BEGIN_MARK} 标记块"
    return 1
  fi
  chmod +x "$out"
  log "已生成自包含: $out"
}

main() {
  mkdir -p "$OUT_DIR"
  build_one "${HERE}/install.sh"   "${OUT_DIR}/install.sh"
  build_one "${HERE}/uninstall.sh" "${OUT_DIR}/uninstall.sh"

  # 自检：语法 + 确认无残留 source 行
  local f
  for f in install.sh uninstall.sh; do
    if ! bash -n "${OUT_DIR}/${f}"; then
      log "错误：${f} 语法检查失败"
      exit 1
    fi
    if grep -Eq '^\s*\.\s+"\$\{W9_LIB_DIR\}' "${OUT_DIR}/${f}"; then
      log "错误：${f} 仍包含未内联的 source 语句"
      exit 1
    fi
  done
  log "构建完成，自检通过：${OUT_DIR}/install.sh, ${OUT_DIR}/uninstall.sh"
}

main "$@"
