FROM ansible/ansible:centos7

LABEL Description="DevOps for ansible runtime" Vendor="Websoft9" Version="1.0.0"

WORKDIR "/ansible"

# Install ansible
RUN yum install ansible -y

# Install role_common
RUN git clone https://github.com/Websoft9/role_common
RUN ansible-playbook role_common/tests/test.yml

# download template of role, it's to run the tasks of you want to test
RUN git clone https://github.com/Websoft9/role_template

VOLUME "/ansible"

# Define the entry point for the docker container.
CMD ["bash" "-c" "echo ansible RunTime is OK!"]
